<a href="https://colab.research.google.com/github/Hossein97Py/Coursera_Course2/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to Keras and TensorFlow 

---



---


Chapter 3 of the Deep Learning with Python book by François Chollet

In [ ]:
import tensorflow as tf

In [ ]:
X = tf.ones(shape=(2, 1))

In [ ]:
print(X)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


# A Tensor isn't assignable

A significant difference between NumPy arrays and TensorFlow tensors is that Tensor-
Flow tensors aren’t assignable: they’re constant. For instance, in NumPy, you can do
the following.

In [ ]:
import numpy as np
Y = np.ones(shape=(2, 2))
Y[0, 0] = 0
print(Y)

[[0. 1.]
 [1. 1.]]


این کار رو برای یک تنسور نمیتونیم انجام بدیم ولی میتونیم با تنسورفلو یک متغییر بسازیم و بعد با اساین مقدارش رو تغییر بدیم

In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)
v[0, 0].assign(1376)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.9715313 ],
       [ 0.20442016],
       [-2.448335  ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.3760000e+03],
       [ 2.0442016e-01],
       [-2.4483349e+00]], dtype=float32)>


# Youtube Video ==> Tensorflow Introduction