<a href="https://colab.research.google.com/github/Hossein97Py/Coursera_Course2/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Introduction to Keras and TensorFlow 

---



# Chapter 3 of the Deep Learning with Python book by François Chollet

In [ ]:
import tensorflow as tf

In [ ]:
X = tf.ones(shape=(2, 1))

In [ ]:
print(X)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


## A Tensor isn't assignable

A significant difference between NumPy arrays and TensorFlow tensors is that Tensor-
Flow tensors aren’t assignable: they’re constant. For instance, in NumPy, you can do
the following.

In [ ]:
import numpy as np
Y = np.ones(shape=(2, 2))
Y[0, 0] = 0
print(Y)

[[0. 1.]
 [1. 1.]]


این کار رو برای یک تنسور نمیتونیم انجام بدیم ولی میتونیم با تنسورفلو یک متغییر بسازیم و بعد با اساین مقدارش رو تغییر بدیم

In [ ]:
v = tf.Variable(initial_value=tf.random.normal(shape=(3, 1)))
print(v)
v[0, 0].assign(1376)
print(v)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.9715313 ],
       [ 0.20442016],
       [-2.448335  ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.3760000e+03],
       [ 2.0442016e-01],
       [-2.4483349e+00]], dtype=float32)>


# Youtube Video ==> Tensorflow Introduction

Tensor: "A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes."

TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape.

Data Types Include: float32, int32, string and others.

Shape: Represents the dimension of data.

ساخت تنسور: برای ساخت مقدار و نوع تنسور رو مشخص میکنیم. معمولا تنسورها عددی هستند و به ندرت تنسور متنی داریم

In [19]:
import tensorflow as tf
string1 = tf.Variable("Hi, This is string", tf.string)
number1 = tf.Variable(324, tf.int16)
floating1 = tf.Variable(3.567, tf.float64)
print(string1, number1, floating1)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Hi, This is string'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


تنسورها رنک یا درجه دارند که درواقع میشه همون ابعادشون. مثلا این تنسور بالایی‌ها رنک صفر یا اسکالر بودن

A rank two tensor is what we typically think of as a matrix, a rank one tensor is a vector. For a rank two tensor you can access any element with the syntax t[i, j]. For a rank three tensor you would need to address an element with t[i, j, k].

In [20]:
rank1_tensor = tf.Variable(["Test"], tf.string)
rank2_tensor = tf.Variable([["test", "OK"], ["test", "yes"]], tf.string)
print(rank2_tensor)
tf.rank(rank2_tensor)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'test', b'OK'],
       [b'test', b'yes']], dtype=object)>


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [21]:
rank2_tensor.shape

TensorShape([2, 2])

In [22]:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


این تنسور رنک 2 هست با شیپ 4 در 5

In [23]:
column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


ما چهار نوع تنسور داریم که وریبل یک نوع شون هست. بقیه تنسورها تغییر ناپذیر هستن

###Types of Tensors
Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.
- Variable
- Constant
- Placeholder
- SparseTensor

With the execption of ```Variable``` all these tensors are immuttable, meaning their value may not change during execution.